version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"

  # database:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #   volumes:
  #     - ./data:/var/lib/mysql
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
